name: Docker Build and Push

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Name of the Docker image (e.g., gwiazdeczkowe/api)'
        required: true
        type: string
      dockerfile_path:
        description: 'Path to Dockerfile'
        required: false
        type: string
        default: 'Dockerfile'
      context_path:
        description: 'Build context path'
        required: false
        type: string
        default: '.'
      version:
        description: 'Version tag for the image'
        required: true
        type: string
      registry:
        description: 'Docker registry URL'
        required: false
        type: string
        default: '192.168.1.6:30500'
    secrets:
      REGISTRY_USERNAME:
        description: 'Docker registry username (optional for private registries)'
        required: false
      REGISTRY_PASSWORD:
        description: 'Docker registry password (optional for private registries)'
        required: false

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context_path }}
          file: ${{ inputs.dockerfile_path }}
          push: true
          tags: |
            ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.version }}
            ${{ inputs.registry }}/${{ inputs.image_name }}:latest
          cache-from: type=registry,ref=${{ inputs.registry }}/${{ inputs.image_name }}:buildcache
          cache-to: type=registry,ref=${{ inputs.registry }}/${{ inputs.image_name }}:buildcache,mode=max
          build-args: |
            VERSION=${{ inputs.version }}

      - name: Image Summary
        run: |
          echo "### Docker Image Built Successfully! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Image:** \`${{ inputs.registry }}/${{ inputs.image_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Tags:**" >> $GITHUB_STEP_SUMMARY
          echo "- \`${{ inputs.version }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- \`latest\`" >> $GITHUB_STEP_SUMMARY
