name: Helm Deploy

on:
  workflow_call:
    inputs:
      chart_path:
        description: 'Path to Helm chart'
        required: true
        type: string
      release_name:
        description: 'Helm release name'
        required: true
        type: string
      namespace:
        description: 'Kubernetes namespace'
        required: false
        type: string
        default: 'gwiazdeczkowe-animacje'
      version:
        description: 'Application version to deploy'
        required: true
        type: string
      values_file:
        description: 'Path to values file (optional)'
        required: false
        type: string
        default: ''
      create_namespace:
        description: 'Create namespace if it does not exist'
        required: false
        type: boolean
        default: false
      timeout:
        description: 'Timeout for helm operations'
        required: false
        type: string
        default: '10m'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Verify Kubeconfig exists
        run: |
          if [ ! -f $HOME/.kube/config ]; then
            echo "Error: kubeconfig not found at $HOME/.kube/config"
            exit 1
          fi
          chmod 600 $HOME/.kube/config

      - name: Verify Kubernetes connection
        run: |
          kubectl version --client
          kubectl cluster-info

      - name: Update Helm chart version
        run: |
          # Update image tag in values.yaml
          sed -i "s/tag: .*/tag: \"${{ inputs.version }}\"/" ${{ inputs.chart_path }}/values.yaml

          # Update fullnameOverride to include version
          VERSION_SLUG=$(echo "${{ inputs.version }}" | tr '.' '-')
          sed -i "s/fullnameOverride: .*/fullnameOverride: \"${{ inputs.release_name }}-v${VERSION_SLUG}\"/" ${{ inputs.chart_path }}/values.yaml

      - name: Helm lint
        run: |
          helm lint ${{ inputs.chart_path }}

      - name: Helm upgrade/install
        run: |
          HELM_CMD="helm upgrade --install ${{ inputs.release_name }} ${{ inputs.chart_path }} \
            --namespace ${{ inputs.namespace }} \
            --values values.yaml \
            --timeout ${{ inputs.timeout }} \
            --wait"

          if [ "${{ inputs.create_namespace }}" = "true" ]; then
            HELM_CMD="$HELM_CMD --create-namespace"
          fi

          if [ -n "${{ inputs.values_file }}" ]; then
            HELM_CMD="$HELM_CMD --values ${{ inputs.values_file }}"
          fi

          eval $HELM_CMD

      - name: Verify deployment
        run: |
          kubectl get pods -n ${{ inputs.namespace }} -l app.kubernetes.io/name=${{ inputs.release_name }}
          kubectl get services -n ${{ inputs.namespace }} -l app.kubernetes.io/name=${{ inputs.release_name }}

      - name: Deployment Summary
        run: |
          echo "### Helm Deployment Successful! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Release:** \`${{ inputs.release_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Namespace:** \`${{ inputs.namespace }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** \`${{ inputs.version }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Chart:** \`${{ inputs.chart_path }}\`" >> $GITHUB_STEP_SUMMARY
